### ISSUE TITLE
Formating automático de snippets

### ISSUE THREAD

**Issue by TomRolB** [Al-Fajor/printscript#142]
Como administrador
 Quiero que al habilitar una regla de formateo se formateen todos los snippets
 automáticamente
 Para que todos los snippets siempre cumplan las reglas de estilo.

 Notas:

-  El administrador no debe tener que esperar a que se formateen los snippets cada vez que habilita una regla.
-  Al ser un proceso que puede ser largo ya que el administrador tiene muchos snippets, el proceso debe ser tolerante a fallos. En caso de que falla, el proceso debe reanudar desde dónde falló o salteando el snippet que causó la falla si hubiera

**Comment by FranCalveyra** [comment]
Esto está totalmente ligado a `Redis`
