### ISSUE TITLE
Redis + Linting automático de snippets

### ISSUE THREAD

**Issue by TomRolB** [Al-Fajor/printscript#145]
Como administrador
 Quiero que al modificar una regla de linting se evalúen todos los snippets automáticamente
 Para poder ver cuales de mis snippets respetan las reglas y cuáles no.

 Notas:

-  El administrador no debe tener que esperar a que se linteen los snippets cada vez que habilita una regla.
-  Al ser un proceso que puede ser largo ya que el administrador tiene muchos snippets, el proceso debe ser tolerante a fallos. En caso de que falla, el proceso debe reanudar desde dónde falló o salteando el snippet que causó la falla si hubiera

**Comment by FranCalveyra** [comment]
Esto está totalmente ligado a `Redis`
